### ISSUE TITLE
java -jar VUE.jar don´t work on ubuntu 22.04 with openjdk 11

### ISSUE THREAD

**Issue by ocanor** [VUE/VUE#60]
$ java -jar VUE.jar 
VUE 2022-07-13 00:46:58,261  INFO [main] VUE: VUE build: October 8 2015 at 1658 by tomadm on Linux 2.6.32-504.23.4.el6.x86_64 i386 JVM 1.7.0_21-b11(bits=32)
VUE 2022-07-13 00:46:58,262  INFO [main] VUE: Current Platform: Linux 5.15.0-41-generic amd64
VUE 2022-07-13 00:46:58,270  INFO [main] VUE: Running JVM: 11.0.15+10-Ubuntu-0ubuntu0.22.04.1 / 64 bit; MaxMemory(-Xmx)=3980,0M, CurMemory(-Xms)=252,0M, FreeMemory=187,5M
VUE 2022-07-13 00:46:58,270  INFO [main] VUE: VUE version: 3.3.0
VUE 2022-07-13 00:46:58,270  INFO [main] VUE: Current Working Directory: /opt/vue
VUE 2022-07-13 00:46:58,270  INFO [main] VUE: User/host: ocanor@null
VUE 2022-07-13 00:46:58,374  INFO [main] [init] Images: created thread pool: tufts.vue.Images$PriorityThreadPool@48b67364[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]; maxSize=7
VUE 2022-07-13 00:46:58,782  INFO [main] [init] [build] RDFIndex: "http://vue.tufts.edu/ontology/vue.rdfs#" <- VUE_ONTOLOGY
VUE 2022-07-13 00:46:58,782  INFO [main] [init] [build] RDFIndex: "http://vue.tufts.edu/vue.rdfs#" <- VUE_GENERAL_NAMESPACE
VUE 2022-07-13 00:46:58,783  INFO [main] [init] [build] RDFIndex: "http://vue.tufts.edu/vue.rdfs#none" <- ONTOLOGY_NONE java.lang.String@019ae6bb
VUE 2022-07-13 00:46:58,783  INFO [main] [init] [build] VueMetadataElement: ONTOLOGY_NONE "http://vue.tufts.edu/vue.rdfs#none" java.lang.String@019ae6bb
VUE 2022-07-13 00:46:58,811  INFO [main] [init] [build] MetadataList: ONTOLOGY_NONE "http://vue.tufts.edu/vue.rdfs#none" java.lang.String@019ae6bb
VUE 2022-07-13 00:46:58,996  INFO [main] [init] [build] Mapping: Loading mapping descriptors from jar:file:/opt/vue/VUE.jar!/tufts/vue/resources/lw_mapping_1_1.xml
VUE 2022-07-13 00:46:59,190  INFO [Thread-1] CategoryModel: no custom meta-data: /home/ocanor/.vue_2/custom.rdfs (No existe el archivo o el directorio)
VUE 2022-07-13 00:46:59,309 ERROR [main] [init] [build] OntManager: OntManager.save: java.io.FileNotFoundException: /home/ocanor/.vue_2/ontology.xml (No existe el archivo o el directorio)
VUE 2022-07-13 00:46:59,618  WARN [main] [init] [build] EditorManager: editor not ready to produce value: tufts.vue.FontEditorPanel$17@5aaaa446[tufts.vue.FontEditorPanel$17:LWPropertyHandler[font.style=java.lang.NullPointerException]]; java.lang.NullPointerException
VUE 2022-07-13 00:46:59,619  WARN [main] [init] [build] EditorManager: editor not ready to produce value: tufts.vue.FontEditorPanel$18@08deb645[tufts.vue.FontEditorPanel$18:LWPropertyHandler[font.underline=java.lang.NullPointerException]]; java.lang.NullPointerException
java.lang.ArrayIndexOutOfBoundsException: No such child: 1; in Thread[main,5,main] at 1657691219695 Wed Jul 13 00:46:59 CDT 2022
	at java.desktop/java.awt.Container.getComponent(Container.java:350) 
	at tufts.vue.VUE$29.addNotify(VUE.java:2847) 
	at java.desktop/java.awt.Container.addImpl(Container.java:1146) 
	at java.desktop/java.awt.Container.add(Container.java:997) 
	at tufts.vue.gui.VueFrame.addComp(VueFrame.java:351) 
	at tufts.vue.VUE.buildApplicationInterface(VUE.java:1641) 
	at tufts.vue.VUE.initApplication(VUE.java:1302) 
	at tufts.vue.VUE.main(VUE.java:1063) 
END java.lang.ArrayIndexOutOfBoundsException: No such child: 1

VUE 2022-07-13 00:46:59,708  WARN [main] [init] [build] LWComponent: setCreated erasing 1657691219706=Wed Jul 13 00:46:59 CDT 2022 with: 1657691219708=Wed Jul 13 00:46:59 CDT 2022; LWMap[v-1 Nuevo Mapa n=0]
VUE 2022-07-13 00:46:59,710  INFO [main] [init] [build] VUE: displayMap LWMap[v-1 Nuevo Mapa n=1]
VUE 2022-07-13 00:46:59,744  WARN [main] [init] LayersUI: getActiveLayer when map is null
VUE 2022-07-13 00:46:59,744  INFO [main] VUE: UI startup completed.
VUE 2022-07-13 00:46:59,745  INFO [main] [initDS] UrlAuthentication: instanced; listening to VDSM
VUE 2022-07-13 00:46:59,746  INFO [main] [initDS] VueDataSourceManager: Installed DataSources not found; missing /home/ocanor/.vue_2/InstalledDataSources.xml
VUE 2022-07-13 00:46:59,746  INFO [main] [initDS] VueDataSourceManager: configuring data sources; n=0
VUE 2022-07-13 00:46:59,746  INFO [main] [initDS] VueDataSourceManager: Installed DataSources not found; missing /home/ocanor/.vue_2/InstalledDataSources.xml
VUE 2022-07-13 00:46:59,746  INFO [main] VUE: main complete
VUE 2022-07-13 00:47:00,153  INFO [AWT-EventQueue-0] [DSV] DataSourceViewer: requesting installed data sources from VDSM
VUE 2022-07-13 00:47:00,154  INFO [AWT-EventQueue-0] [DSV] VueDataSourceManager: Installed DataSources not found; missing /home/ocanor/.vue_2/InstalledDataSources.xml
VUE 2022-07-13 00:47:00,158  INFO [AWT-EventQueue-0] [DSV] VueFederatedSearchManager: listing /Library/Caches/OSID to find "Extensions.xml"
VUE 2022-07-13 00:47:00,167  INFO [AWT-EventQueue-0] [DSV] DataSourceViewer: Loading old style data sources...
VUE 2022-07-13 00:47:00,218  INFO [AWT-EventQueue-0] [DSV] DataSourceViewer: Loaded old style data sources.
VUE 2022-07-13 00:47:00,222  INFO [version-check] VUE: Checking for latest version of VUE
VUE 2022-07-13 00:47:00,223  INFO [AWT-EventQueue-0] MapViewer: pre-cache run "Nuevo Mapa": java.util.LinkedHashSet@68a088f8[size=0]
[Fatal Error] :1:1: Final de archivo prematuro.
VUE 2022-07-13 00:47:00,497 ERROR [version-check] VUE: Error Checking latest VUE release:
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Final de archivo prematuro.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathImplUtil.getDocument(XPathImplUtil.java:133)
	at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:119)
	at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:129)
	at tufts.vue.VUE.checkLatestVersion(VUE.java:3835)
	at tufts.vue.VUE$13.run(VUE.java:1162)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Final de archivo prematuro.
	at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathImplUtil.getDocument(XPathImplUtil.java:135)
	at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:119)
	at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:129)
	at tufts.vue.VUE.checkLatestVersion(VUE.java:3835)
	at tufts.vue.VUE$13.run(VUE.java:1162)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Final de archivo prematuro.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathImplUtil.getDocument(XPathImplUtil.java:133)
	... 4 more

**Comment by ocanor** [comment]
when try compile
$ ant
Buildfile: ~/VUE-3.3.0/VUE2/src/build.xml

vue:
     [java] Error: no se ha encontrado o cargado la clase principal tufts.vue.VUE
     [java] Causado por: java.lang.ClassNotFoundException: tufts.vue.VUE

BUILD FAILED
~/VUE-3.3.0/VUE2/src/build.xml:1321: Java returned: 1

Total time: 0 seconds

**Comment by m-e-leypold** [comment]
I think you need to run 'ant compile' then 'ant' starts the application.
