### ISSUE TITLE
After starting without argument then opening from recent: Exception, no open.

### ISSUE THREAD

**Issue by m-e-leypold** [VUE/VUE#73]
I start vue from the jar, without further file arguments. Then I open from recent and get the backtrace below. The file doesn't open. But opening from recent a second time succeeds.

I used a version I built from masterm but this behaviour already is in the 3.0.0 version from 2015 if I remember right.

Backtrace:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0; in Thread[AWT-EventQueue-0,6,main] at 1715292402927 Fri May 10 00:06:42 CEST 2024
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) 
	at java.util.ArrayList.get(ArrayList.java:435) 
	at javax.swing.JTabbedPane.setForegroundAt(JTabbedPane.java:1495) 
	at tufts.vue.MapTabbedPane.fireStateChanged(MapTabbedPane.java:116) 
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) 
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) 
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) 
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) 
	at javax.swing.JTabbedPane.removeTabAt(JTabbedPane.java:979) 
	at tufts.vue.MapTabbedPane.closeMap(MapTabbedPane.java:473) 
	at tufts.vue.VUE.closeMap(VUE.java:3271) 
	at tufts.vue.VUE.closeMap(VUE.java:3261) 
	at tufts.vue.VUE.displayMap(VUE.java:3377) 
	at tufts.vue.action.OpenAction.displayMap(OpenAction.java:81) 
	at tufts.vue.gui.VueMenuBar$RecentOpenAction.act(VueMenuBar.java:1305) 
	at tufts.vue.VueAction.actionPerformed(VueAction.java:361) 
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) 
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) 
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) 
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) 
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) 
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:882) 
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:926) 
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) 
	at java.awt.Component.processMouseEvent(Component.java:6539) 
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) 
	at java.awt.Component.processEvent(Component.java:6304) 
	at java.awt.Container.processEvent(Container.java:2239) 
	at java.awt.Component.dispatchEventImpl(Component.java:4889) 
	at java.awt.Container.dispatchEventImpl(Container.java:2297) 
	at java.awt.Component.dispatchEvent(Component.java:4711) 
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) 
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535) 
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) 
	at java.awt.Container.dispatchEventImpl(Container.java:2283) 
	at java.awt.Window.dispatchEventImpl(Window.java:2746) 
	at java.awt.Component.dispatchEvent(Component.java:4711) 
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) 
	at java.awt.EventQueue.access$500(EventQueue.java:97) 
	at java.awt.EventQueue$3.run(EventQueue.java:709) 
	at java.awt.EventQueue$3.run(EventQueue.java:703) 
	at java.security.AccessController.doPrivileged(Native Method) 
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) 
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) 
	at java.awt.EventQueue$4.run(EventQueue.java:733) 
	at java.awt.EventQueue$4.run(EventQueue.java:731) 
	at java.security.AccessController.doPrivileged(Native Method) 
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) 
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) 
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) 
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
END java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

```

**Comment by m-e-leypold** [comment]
I can also open from recent if I passed a file argument to view, so I already have another map open.

**Comment by rpavlik** [comment]
See one of the other issues, I have fixed this in my fork but upstream is nonresponsive and hasn't merged a fix.
